# Generated by Django 4.2.20 on 2025-04-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_orderplacement_cash_on_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplacement',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='orderplacement',
            name='cash_on_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
