# Generated by Django 4.2.20 on 2025-04-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderplacement_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplacement',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='orderplacement',
            name='payment_status',
        ),
    ]
